// -----------------------------------------------------------------------------
// File      : dma_csr.v
// Brief     : Auto-generated by autowire.py v2.0
// Author    : czz
// Date      : 2025-09-07 12:15:43
// -----------------------------------------------------------------------------

module dma_csr(
    // u_apb2reg_if ports
    input           clk,
    input           rst_n,
    input           psel,
    input           penable,
    input           pwrite,
    input   [11:0]  paddr,
    input   [31:0]  pwdata,
    output  [31:0]  prdata,
    output          pready,
    output          pslverr,

    // u_dma_reg ports
    input   [15:0]  csr_dma_version,
    output          csr_dma_start,
    output  [7:0]   csr_dma_maxburst,
    output  [31:0]  csr_dma_single_trans_bytes,
    output  [31:0]  csr_dma_total_trans_bytes,
    output  [31:0]  csr_src_addr,
    output  [31:0]  csr_dst_addr,
    output  [15:0]  csr_src_jump_num,
    output  [15:0]  csr_dst_jump_num,
    output  [31:0]  csr_src_jump_gap,
    output  [31:0]  csr_dst_jump_gap,
    input   [15:0]  csr_src_jump_state,
    input   [15:0]  csr_dst_jump_state,
    input   [1:0]   csr_dma_status,
    input           csr_dma_err,
    input           csr_dma_done,
    output          csr_dma_err_clr,
    input   [1:0]   csr_dma_err_type,
    input   [31:0]  csr_dma_err_addr
);

wire  [31:0]  rd_data ;
wire          rd_en   ;
wire  [11:0]  reg_addr;
wire  [31:0]  wr_data ;
wire          wr_en   ;
wire  [3:0]   wr_msk  ;

// Instance: u_apb2reg_if (apb2reg_if)
apb2reg_if u_apb2reg_if (
    .pclk                       (clk                       ),    // input 
    .presetn                    (rst_n                     ),    // input 
    .psel                       (psel                      ),    // input 
    .penable                    (penable                   ),    // input 
    .pwrite                     (pwrite                    ),    // input 
    .paddr                      (paddr                     ),    // input  [11:0]
    .pwdata                     (pwdata                    ),    // input  [31:0]
    .prdata                     (prdata                    ),    // output [31:0]
    .pready                     (pready                    ),    // output
    .pslverr                    (pslverr                   ),    // output
    .reg_addr                   (reg_addr                  ),    // output [11:0]
    .wr_en                      (wr_en                     ),    // output
    .rd_en                      (rd_en                     ),    // output
    .wr_msk                     (wr_msk                    ),    // output [3:0]
    .wr_data                    (wr_data                   ),    // output [31:0]
    .rd_data                    (rd_data                   )     // input  [31:0]
);

// Instance: u_dma_reg (dma_reg)
dma_reg u_dma_reg (
    .clk                        (clk                       ),    // input 
    .rst_n                      (rst_n                     ),    // input 
    .reg_addr                   (reg_addr                  ),    // input  [11:0]
    .wr_en                      (wr_en                     ),    // input 
    .rd_en                      (rd_en                     ),    // input 
    .wr_msk                     (wr_msk                    ),    // input  [3:0]
    .wr_data                    (wr_data                   ),    // input  [31:0]
    .rd_data                    (rd_data                   ),    // output [31:0]
    .csr_dma_version            (csr_dma_version           ),    // input  [15:0]
    .csr_dma_start              (csr_dma_start             ),    // output
    .csr_dma_maxburst           (csr_dma_maxburst          ),    // output [7:0]
    .csr_dma_single_trans_bytes (csr_dma_single_trans_bytes),    // output [31:0]
    .csr_dma_total_trans_bytes  (csr_dma_total_trans_bytes ),    // output [31:0]
    .csr_src_addr               (csr_src_addr              ),    // output [31:0]
    .csr_dst_addr               (csr_dst_addr              ),    // output [31:0]
    .csr_src_jump_num           (csr_src_jump_num          ),    // output [15:0]
    .csr_dst_jump_num           (csr_dst_jump_num          ),    // output [15:0]
    .csr_src_jump_gap           (csr_src_jump_gap          ),    // output [31:0]
    .csr_dst_jump_gap           (csr_dst_jump_gap          ),    // output [31:0]
    .csr_src_jump_state         (csr_src_jump_state        ),    // input  [15:0]
    .csr_dst_jump_state         (csr_dst_jump_state        ),    // input  [15:0]
    .csr_dma_status             (csr_dma_status            ),    // input  [1:0]
    .csr_dma_err                (csr_dma_err               ),    // input 
    .csr_dma_done               (csr_dma_done              ),    // input 
    .csr_dma_err_clr            (csr_dma_err_clr           ),    // output
    .csr_dma_err_type           (csr_dma_err_type          ),    // input  [1:0]
    .csr_dma_err_addr           (csr_dma_err_addr          )     // input  [31:0]
);

endmodule