// -----------------------------------------------------------------------------
// File      : dma_core.v
// Brief     : Auto-generated by autowire.py v2.0
// Author    : czz
// Date      : 2025-09-07 12:15:41
// -----------------------------------------------------------------------------

module dma_core(
    // u_dma_fsm ports
    input           clk,
    input           rst_n,
    input   [31:0]  csr_dma_single_trans_bytes,
    input   [31:0]  csr_dma_total_trans_bytes,
    input   [31:0]  csr_src_addr,
    input   [31:0]  csr_dst_addr,
    input   [15:0]  csr_src_jump_num,
    input   [15:0]  csr_dst_jump_num,
    input   [31:0]  csr_src_jump_gap,
    input   [31:0]  csr_dst_jump_gap,
    output  [15:0]  csr_src_jump_state,
    output  [15:0]  csr_dst_jump_state,
    input           csr_dma_start,
    output          csr_dma_done,
    output  [1:0]   csr_dma_status,
    input           csr_dma_err_clr,
    output          csr_dma_err,
    output  [1:0]   csr_dma_err_type,
    output  [31:0]  csr_dma_err_addr,

    // u_dma_rd_slice ports
    input   [7:0]   csr_dma_maxburst,

    // u_dma_axi2fifo ports
    output          axim_awlock,
    output  [3:0]   axim_awcache,
    output  [2:0]   axim_awprot,
    output  [3:0]   axim_awqos,
    output  [31:0]  axim_awaddr,
    output  [7:0]   axim_awlen,
    output  [2:0]   axim_awsize,
    output  [1:0]   axim_awburst,
    output          axim_awvalid,
    input           axim_awready,
    output  [63:0]  axim_wdata,
    output  [7:0]   axim_wstrb,
    output          axim_wlast,
    output          axim_wvalid,
    input           axim_wready,
    input   [1:0]   axim_bresp,
    input           axim_bvalid,
    output          axim_bready,
    output          axim_arlock,
    output  [3:0]   axim_arcache,
    output  [2:0]   axim_arprot,
    output  [3:0]   axim_arqos,
    output  [31:0]  axim_araddr,
    output  [7:0]   axim_arlen,
    output  [2:0]   axim_arsize,
    output  [1:0]   axim_arburst,
    output          axim_arvalid,
    input           axim_arready,
    input   [63:0]  axim_rdata,
    input   [1:0]   axim_rresp,
    input           axim_rlast,
    input           axim_rvalid,
    output          axim_rready,
    output  [7:0]   axim_awid,
    input   [7:0]   axim_bid,
    output  [7:0]   axim_arid,
    input   [7:0]   axim_rid
);

wire  [31:0]  dma_axi_err_addr     ;
wire          dma_axi_err_type     ;
wire          dma_axi_err_valid    ;
wire          dma_axi_pending      ;
wire  [31:0]  dma_axi_rd_req_addr  ;
wire  [7:0]   dma_axi_rd_req_alen  ;
wire  [2:0]   dma_axi_rd_req_size  ;
wire  [7:0]   dma_axi_rd_req_strb  ;
wire          dma_axi_rd_req_valid ;
wire          dma_axi_rd_resp_ready;
wire  [31:0]  dma_axi_wr_req_addr  ;
wire  [7:0]   dma_axi_wr_req_alen  ;
wire  [2:0]   dma_axi_wr_req_size  ;
wire  [7:0]   dma_axi_wr_req_strb  ;
wire          dma_axi_wr_req_valid ;
wire          dma_axi_wr_resp_ready;
wire  [31:0]  dma_rd_length        ;
wire          dma_rd_slice_done    ;
wire          dma_rd_slice_valid   ;
wire  [31:0]  dma_rd_start_addr    ;
wire  [31:0]  dma_tx_length        ;
wire          dma_tx_slice_done    ;
wire          dma_tx_slice_valid   ;
wire  [31:0]  dma_tx_start_addr    ;

// Instance: u_dma_fsm (dma_fsm)
dma_fsm #(
    .DMA_ADDR_WIDTH(32),
    .DMA_DATA_WIDTH(64)
) u_dma_fsm (
    .clk                        (clk                       ),    // input 
    .rst_n                      (rst_n                     ),    // input 
    .csr_dma_single_trans_bytes (csr_dma_single_trans_bytes),    // input  [31:0]
    .csr_dma_total_trans_bytes  (csr_dma_total_trans_bytes ),    // input  [31:0]
    .csr_src_addr               (csr_src_addr              ),    // input  [31:0]
    .csr_dst_addr               (csr_dst_addr              ),    // input  [31:0]
    .csr_src_jump_num           (csr_src_jump_num          ),    // input  [15:0]
    .csr_dst_jump_num           (csr_dst_jump_num          ),    // input  [15:0]
    .csr_src_jump_gap           (csr_src_jump_gap          ),    // input  [31:0]
    .csr_dst_jump_gap           (csr_dst_jump_gap          ),    // input  [31:0]
    .csr_src_jump_state         (csr_src_jump_state        ),    // output [15:0]
    .csr_dst_jump_state         (csr_dst_jump_state        ),    // output [15:0]
    .csr_dma_start              (csr_dma_start             ),    // input 
    .csr_dma_done               (csr_dma_done              ),    // output
    .csr_dma_status             (csr_dma_status            ),    // output [1:0]
    .csr_dma_err_clr            (csr_dma_err_clr           ),    // input 
    .csr_dma_err                (csr_dma_err               ),    // output
    .csr_dma_err_type           (csr_dma_err_type          ),    // output [1:0]
    .csr_dma_err_addr           (csr_dma_err_addr          ),    // output [31:0]
    .dma_axi_err_valid          (dma_axi_err_valid         ),    // input 
    .dma_axi_err_addr           (dma_axi_err_addr          ),    // input  [31:0]
    .dma_axi_err_type           (dma_axi_err_type          ),    // input 
    .dma_rd_length              (dma_rd_length             ),    // output [31:0]
    .dma_rd_start_addr          (dma_rd_start_addr         ),    // output [31:0]
    .dma_rd_slice_valid         (dma_rd_slice_valid        ),    // output
    .dma_rd_slice_done          (dma_rd_slice_done         ),    // input 
    .dma_tx_length              (dma_tx_length             ),    // output [31:0]
    .dma_tx_start_addr          (dma_tx_start_addr         ),    // output [31:0]
    .dma_tx_slice_valid         (dma_tx_slice_valid        ),    // output
    .dma_tx_slice_done          (dma_tx_slice_done         ),    // input 
    .dma_axi_pending            (dma_axi_pending           )     // input 
);

// Instance: u_dma_rd_slice (dma_slice)
dma_slice #(
    .DMA_ADDR_WIDTH(32),
    .DMA_DATA_WIDTH(64)
) u_dma_rd_slice (
    .clk                        (clk                       ),    // input 
    .rst_n                      (rst_n                     ),    // input 
    .csr_dma_maxburst           (csr_dma_maxburst          ),    // input  [7:0]
    .dma_axi_req_valid          (dma_axi_rd_req_valid      ),    // output
    .dma_axi_req_addr           (dma_axi_rd_req_addr       ),    // output [31:0]
    .dma_axi_req_strb           (dma_axi_rd_req_strb       ),    // output [7:0]
    .dma_axi_req_size           (dma_axi_rd_req_size       ),    // output [2:0]
    .dma_axi_req_alen           (dma_axi_rd_req_alen       ),    // output [7:0]
    .dma_axi_resp_ready         (dma_axi_rd_resp_ready     ),    // input 
    .dma_addr                   (dma_rd_start_addr         ),    // input  [31:0]
    .dma_length                 (dma_rd_length             ),    // input  [31:0]
    .dma_slice_valid            (dma_rd_slice_valid        ),    // input 
    .dma_slice_done             (dma_rd_slice_done         )     // output
);

// Instance: u_dma_tx_slice (dma_slice)
dma_slice #(
    .DMA_ADDR_WIDTH(32),
    .DMA_DATA_WIDTH(64)
) u_dma_tx_slice (
    .clk                        (clk                       ),    // input 
    .rst_n                      (rst_n                     ),    // input 
    .csr_dma_maxburst           (csr_dma_maxburst          ),    // input  [7:0]
    .dma_axi_req_valid          (dma_axi_wr_req_valid      ),    // output
    .dma_axi_req_addr           (dma_axi_wr_req_addr       ),    // output [31:0]
    .dma_axi_req_strb           (dma_axi_wr_req_strb       ),    // output [7:0]
    .dma_axi_req_size           (dma_axi_wr_req_size       ),    // output [2:0]
    .dma_axi_req_alen           (dma_axi_wr_req_alen       ),    // output [7:0]
    .dma_axi_resp_ready         (dma_axi_wr_resp_ready     ),    // input 
    .dma_addr                   (dma_tx_start_addr         ),    // input  [31:0]
    .dma_length                 (dma_tx_length             ),    // input  [31:0]
    .dma_slice_valid            (dma_tx_slice_valid        ),    // input 
    .dma_slice_done             (dma_tx_slice_done         )     // output
);

// Instance: u_dma_axi2fifo (dma_axi2fifo)
dma_axi2fifo #(
    .DMA_ADDR_WIDTH    (32),
    .DMA_DATA_WIDTH    (64),
    .AXI_ID_WIDTH      (8 ),
    .RD_ADDR_BUFF_DEPTH(8 ),
    .WR_ADDR_BUFF_DEPTH(8 ),
    .DATA_BUFF_DEPTH   (32)
) u_dma_axi2fifo (
    .clk                        (clk                       ),    // input 
    .rst_n                      (rst_n                     ),    // input 
    .axim_awlock                (axim_awlock               ),    // output
    .axim_awcache               (axim_awcache              ),    // output [3:0]
    .axim_awprot                (axim_awprot               ),    // output [2:0]
    .axim_awqos                 (axim_awqos                ),    // output [3:0]
    .axim_awaddr                (axim_awaddr               ),    // output [31:0]
    .axim_awlen                 (axim_awlen                ),    // output [7:0]
    .axim_awsize                (axim_awsize               ),    // output [2:0]
    .axim_awburst               (axim_awburst              ),    // output [1:0]
    .axim_awvalid               (axim_awvalid              ),    // output
    .axim_awready               (axim_awready              ),    // input 
    .axim_wdata                 (axim_wdata                ),    // output [63:0]
    .axim_wstrb                 (axim_wstrb                ),    // output [7:0]
    .axim_wlast                 (axim_wlast                ),    // output
    .axim_wvalid                (axim_wvalid               ),    // output
    .axim_wready                (axim_wready               ),    // input 
    .axim_bresp                 (axim_bresp                ),    // input  [1:0]
    .axim_bvalid                (axim_bvalid               ),    // input 
    .axim_bready                (axim_bready               ),    // output
    .axim_arlock                (axim_arlock               ),    // output
    .axim_arcache               (axim_arcache              ),    // output [3:0]
    .axim_arprot                (axim_arprot               ),    // output [2:0]
    .axim_arqos                 (axim_arqos                ),    // output [3:0]
    .axim_araddr                (axim_araddr               ),    // output [31:0]
    .axim_arlen                 (axim_arlen                ),    // output [7:0]
    .axim_arsize                (axim_arsize               ),    // output [2:0]
    .axim_arburst               (axim_arburst              ),    // output [1:0]
    .axim_arvalid               (axim_arvalid              ),    // output
    .axim_arready               (axim_arready              ),    // input 
    .axim_rdata                 (axim_rdata                ),    // input  [63:0]
    .axim_rresp                 (axim_rresp                ),    // input  [1:0]
    .axim_rlast                 (axim_rlast                ),    // input 
    .axim_rvalid                (axim_rvalid               ),    // input 
    .axim_rready                (axim_rready               ),    // output
    .axim_awid                  (axim_awid                 ),    // output [7:0]
    .axim_bid                   (axim_bid                  ),    // input  [7:0]
    .axim_arid                  (axim_arid                 ),    // output [7:0]
    .axim_rid                   (axim_rid                  ),    // input  [7:0]
    .dma_axi_rd_req_valid       (dma_axi_rd_req_valid      ),    // input 
    .dma_axi_rd_req_addr        (dma_axi_rd_req_addr       ),    // input  [31:0]
    .dma_axi_rd_req_strb        (dma_axi_rd_req_strb       ),    // input  [7:0]
    .dma_axi_rd_req_size        (dma_axi_rd_req_size       ),    // input  [2:0]
    .dma_axi_rd_req_alen        (dma_axi_rd_req_alen       ),    // input  [7:0]
    .dma_axi_rd_resp_ready      (dma_axi_rd_resp_ready     ),    // output
    .dma_axi_wr_req_valid       (dma_axi_wr_req_valid      ),    // input 
    .dma_axi_wr_req_addr        (dma_axi_wr_req_addr       ),    // input  [31:0]
    .dma_axi_wr_req_strb        (dma_axi_wr_req_strb       ),    // input  [7:0]
    .dma_axi_wr_req_size        (dma_axi_wr_req_size       ),    // input  [2:0]
    .dma_axi_wr_req_alen        (dma_axi_wr_req_alen       ),    // input  [7:0]
    .dma_axi_wr_resp_ready      (dma_axi_wr_resp_ready     ),    // output
    .axi_pending                (dma_axi_pending           ),    // output
    .dma_axi_err_clr            (csr_dma_err_clr           ),    // input 
    .dma_axi_err_valid          (dma_axi_err_valid         ),    // output
    .dma_axi_err_addr           (dma_axi_err_addr          ),    // output [31:0]
    .dma_axi_err_type           (dma_axi_err_type          )     // output
);

endmodule