// -----------------------------------------------------------------------------
// File      : eth_top.v
// Brief     : Auto-generated by autowire.py v2.0
// Author    : czz
// Date      : 2025-08-25 10:16:29
// -----------------------------------------------------------------------------

module eth_top(
    // u_DWC_ether_qos ports
    input            clk_tx_i,
    input            clk_rx_i,
    input            clk_csr_i,
    input            clk_tx_125_i,
    input            clk_rmii_i,
    input            clk_rx_125_i,
    input            clk_tx_180_i,
    input            clk_rx_180_i,
    input            clk_ptp_ref_i,
    output           rst_clk_tx_n_o,
    output           rst_clk_rx_n_o,
    output           rst_clk_app_n_o,
    output  [1:0]    mac_speed_o,
    output  [1:0]    sgmii_link_speed_o,
    input            test_mode,
    output           lpi_intr_o,
    output           sbd_tx_clk_gating_ctrl_o,
    input            pwr_isolate_i,
    input            pwr_clamp_ctrl_i,
    input            pwr_down_ctrl_i,
    input   [2:0]    phy_intf_sel_i,
    output           gmii_mdc_o,
    input            gmii_mdi_i,
    output           gmii_mdo_o,
    output           gmii_mdo_o_e,
    input            phy_intr_i,
    output           sbd_intr_o,
    output  [6:0]    twc_wr_addr_o,
    output           twc_wr_csn_o,
    output  [132:0]  twc_wr_data_o,
    output           twc_wr_en_o,
    output  [6:0]    trc_rd_addr_o,
    output           trc_rd_csn_o,
    input   [132:0]  trc_rd_data_i,
    output           trc_rd_en_o,
    output  [6:0]    rwc_wr_addr_o,
    output           rwc_wr_csn_o,
    output  [132:0]  rwc_wr_data_o,
    output           rwc_wr_en_o,
    output  [6:0]    rrc_rd_addr_o,
    output           rrc_rd_csn_o,
    input   [132:0]  rrc_rd_data_i,
    output           rrc_rd_en_o,
    input            ptp_aux_ts_trig_i,
    input   [63:0]   ptp_timestamp_i,
    output  [63:0]   ptp_timestamp_o,
    output           ptp_pps_o,
    output           sbd_pwr_down_ack_o,
    output           pmt_intr_o,
    output           pcs_acquired_sync_o,
    output           pcs_ewrap_o,
    output           pcs_en_cdet_o,
    output           pcs_lck_ref_o,
    output           phy_txen_o,
    output           phy_txer_o,
    output  [7:0]    phy_txd_o,
    input            phy_rxdv_i,
    input            phy_rxer_i,
    input   [7:0]    phy_rxd_i,
    input            phy_crs_i,
    input            phy_col_i,
    input            aclk_i,
    input            aresetn_i,
    output  [31:0]   awaddr_m_o,
    output  [3:0]    awlen_m_o,
    output  [7:0]    awid_m_o,
    output  [1:0]    awburst_m_o,
    output           awvalid_m_o,
    input            awready_m_i,
    output  [2:0]    awsize_m_o,
    output  [1:0]    awlock_m_o,
    output  [3:0]    awcache_m_o,
    output  [2:0]    awprot_m_o,
    output  [7:0]    wid_m_o,
    output  [127:0]  wdata_m_o,
    output  [15:0]   wstrb_m_o,
    output           wlast_m_o,
    output           wvalid_m_o,
    input            wready_m_i,
    input   [7:0]    bid_m_i,
    input   [1:0]    bresp_m_i,
    input            bvalid_m_i,
    output           bready_m_o,
    output  [31:0]   araddr_m_o,
    output  [3:0]    arlen_m_o,
    output  [7:0]    arid_m_o,
    output  [1:0]    arburst_m_o,
    output           arvalid_m_o,
    input            arready_m_i,
    output  [2:0]    arsize_m_o,
    output  [1:0]    arlock_m_o,
    output  [3:0]    arcache_m_o,
    output  [2:0]    arprot_m_o,
    input   [7:0]    rid_m_i,
    input   [1:0]    rresp_m_i,
    input   [127:0]  rdata_m_i,
    input            rvalid_m_i,
    input            rlast_m_i,
    output           rready_m_o,
    input            csysreq_i,
    output           csysack_o,
    output           cactive_o,
    input            psel_i,
    input   [13:0]   paddr_i,
    input            pwrite_i,
    input   [31:0]   pwdata_i,
    input            penable_i,
    output  [31:0]   prdata_o,
    output           pready_o
);

// Instance: u_DWC_ether_qos (DWC_ether_qos)
DWC_ether_qos u_DWC_ether_qos (
    .clk_tx_i                 (clk_tx_i                ),    // input 
    .clk_rx_i                 (clk_rx_i                ),    // input 
    .clk_csr_i                (clk_csr_i               ),    // input 
    .clk_tx_125_i             (clk_tx_125_i            ),    // input 
    .clk_rmii_i               (clk_rmii_i              ),    // input 
    .clk_rx_125_i             (clk_rx_125_i            ),    // input 
    .clk_tx_180_i             (clk_tx_180_i            ),    // input 
    .clk_rx_180_i             (clk_rx_180_i            ),    // input 
    .clk_ptp_ref_i            (clk_ptp_ref_i           ),    // input 
    .rst_clk_tx_n_o           (rst_clk_tx_n_o          ),    // output
    .rst_clk_rx_n_o           (rst_clk_rx_n_o          ),    // output
    .rst_clk_app_n_o          (rst_clk_app_n_o         ),    // output
    .mac_speed_o              (mac_speed_o             ),    // output [1:0]
    .sgmii_link_speed_o       (sgmii_link_speed_o      ),    // output [1:0]
    .test_mode                (test_mode               ),    // input 
    .lpi_intr_o               (lpi_intr_o              ),    // output
    .sbd_tx_clk_gating_ctrl_o (sbd_tx_clk_gating_ctrl_o),    // output
    .pwr_isolate_i            (pwr_isolate_i           ),    // input 
    .pwr_clamp_ctrl_i         (pwr_clamp_ctrl_i        ),    // input 
    .pwr_down_ctrl_i          (pwr_down_ctrl_i         ),    // input 
    .phy_intf_sel_i           (phy_intf_sel_i          ),    // input  [2:0]
    .gmii_mdc_o               (gmii_mdc_o              ),    // output
    .gmii_mdi_i               (gmii_mdi_i              ),    // input 
    .gmii_mdo_o               (gmii_mdo_o              ),    // output
    .gmii_mdo_o_e             (gmii_mdo_o_e            ),    // output
    .phy_intr_i               (phy_intr_i              ),    // input 
    .sbd_intr_o               (sbd_intr_o              ),    // output
    .twc_wr_addr_o            (twc_wr_addr_o           ),    // output [6:0]
    .twc_wr_csn_o             (twc_wr_csn_o            ),    // output
    .twc_wr_data_o            (twc_wr_data_o           ),    // output [132:0]
    .twc_wr_en_o              (twc_wr_en_o             ),    // output
    .trc_rd_addr_o            (trc_rd_addr_o           ),    // output [6:0]
    .trc_rd_csn_o             (trc_rd_csn_o            ),    // output
    .trc_rd_data_i            (trc_rd_data_i           ),    // input  [132:0]
    .trc_rd_en_o              (trc_rd_en_o             ),    // output
    .rwc_wr_addr_o            (rwc_wr_addr_o           ),    // output [6:0]
    .rwc_wr_csn_o             (rwc_wr_csn_o            ),    // output
    .rwc_wr_data_o            (rwc_wr_data_o           ),    // output [132:0]
    .rwc_wr_en_o              (rwc_wr_en_o             ),    // output
    .rrc_rd_addr_o            (rrc_rd_addr_o           ),    // output [6:0]
    .rrc_rd_csn_o             (rrc_rd_csn_o            ),    // output
    .rrc_rd_data_i            (rrc_rd_data_i           ),    // input  [132:0]
    .rrc_rd_en_o              (rrc_rd_en_o             ),    // output
    .ptp_aux_ts_trig_i        (ptp_aux_ts_trig_i       ),    // input 
    .ptp_timestamp_i          (ptp_timestamp_i         ),    // input  [63:0]
    .ptp_timestamp_o          (ptp_timestamp_o         ),    // output [63:0]
    .ptp_pps_o                (ptp_pps_o               ),    // output
    .sbd_pwr_down_ack_o       (sbd_pwr_down_ack_o      ),    // output
    .pmt_intr_o               (pmt_intr_o              ),    // output
    .pcs_acquired_sync_o      (pcs_acquired_sync_o     ),    // output
    .pcs_ewrap_o              (pcs_ewrap_o             ),    // output
    .pcs_en_cdet_o            (pcs_en_cdet_o           ),    // output
    .pcs_lck_ref_o            (pcs_lck_ref_o           ),    // output
    .phy_txen_o               (phy_txen_o              ),    // output
    .phy_txer_o               (phy_txer_o              ),    // output
    .phy_txd_o                (phy_txd_o               ),    // output [7:0]
    .phy_rxdv_i               (phy_rxdv_i              ),    // input 
    .phy_rxer_i               (phy_rxer_i              ),    // input 
    .phy_rxd_i                (phy_rxd_i               ),    // input  [7:0]
    .phy_crs_i                (phy_crs_i               ),    // input 
    .phy_col_i                (phy_col_i               ),    // input 
    .aclk_i                   (aclk_i                  ),    // input 
    .aresetn_i                (aresetn_i               ),    // input 
    .awaddr_m_o               (awaddr_m_o              ),    // output [31:0]
    .awlen_m_o                (awlen_m_o               ),    // output [3:0]
    .awid_m_o                 (awid_m_o                ),    // output [7:0]
    .awburst_m_o              (awburst_m_o             ),    // output [1:0]
    .awvalid_m_o              (awvalid_m_o             ),    // output
    .awready_m_i              (awready_m_i             ),    // input 
    .awsize_m_o               (awsize_m_o              ),    // output [2:0]
    .awlock_m_o               (awlock_m_o              ),    // output [1:0]
    .awcache_m_o              (awcache_m_o             ),    // output [3:0]
    .awprot_m_o               (awprot_m_o              ),    // output [2:0]
    .wid_m_o                  (wid_m_o                 ),    // output [7:0]
    .wdata_m_o                (wdata_m_o               ),    // output [127:0]
    .wstrb_m_o                (wstrb_m_o               ),    // output [15:0]
    .wlast_m_o                (wlast_m_o               ),    // output
    .wvalid_m_o               (wvalid_m_o              ),    // output
    .wready_m_i               (wready_m_i              ),    // input 
    .bid_m_i                  (bid_m_i                 ),    // input  [7:0]
    .bresp_m_i                (bresp_m_i               ),    // input  [1:0]
    .bvalid_m_i               (bvalid_m_i              ),    // input 
    .bready_m_o               (bready_m_o              ),    // output
    .araddr_m_o               (araddr_m_o              ),    // output [31:0]
    .arlen_m_o                (arlen_m_o               ),    // output [3:0]
    .arid_m_o                 (arid_m_o                ),    // output [7:0]
    .arburst_m_o              (arburst_m_o             ),    // output [1:0]
    .arvalid_m_o              (arvalid_m_o             ),    // output
    .arready_m_i              (arready_m_i             ),    // input 
    .arsize_m_o               (arsize_m_o              ),    // output [2:0]
    .arlock_m_o               (arlock_m_o              ),    // output [1:0]
    .arcache_m_o              (arcache_m_o             ),    // output [3:0]
    .arprot_m_o               (arprot_m_o              ),    // output [2:0]
    .rid_m_i                  (rid_m_i                 ),    // input  [7:0]
    .rresp_m_i                (rresp_m_i               ),    // input  [1:0]
    .rdata_m_i                (rdata_m_i               ),    // input  [127:0]
    .rvalid_m_i               (rvalid_m_i              ),    // input 
    .rlast_m_i                (rlast_m_i               ),    // input 
    .rready_m_o               (rready_m_o              ),    // output
    .csysreq_i                (csysreq_i               ),    // input 
    .csysack_o                (csysack_o               ),    // output
    .cactive_o                (cactive_o               ),    // output
    .psel_i                   (psel_i                  ),    // input 
    .paddr_i                  (paddr_i                 ),    // input  [13:0]
    .pwrite_i                 (pwrite_i                ),    // input 
    .pwdata_i                 (pwdata_i                ),    // input  [31:0]
    .penable_i                (penable_i               ),    // input 
    .prdata_o                 (prdata_o                ),    // output [31:0]
    .pready_o                 (pready_o                )     // output
);

endmodule