// -----------------------------------------------------------------------------
// File      : dma_top.v
// Brief     : Auto-generated by autowire.py v2.0
// Author    : czz
// Date      : 2026-02-05 10:06:35
// -----------------------------------------------------------------------------

module dma_top(
    // u_dma_csr ports
    input           clk,
    input           rst_n,
    input           psel,
    input           penable,
    input           pwrite,
    input   [11:0]  paddr,
    input   [31:0]  pwdata,
    output  [31:0]  prdata,
    output          pready,
    output          pslverr,

    // u_dma_core ports
    output          intr_dma_done,
    output          intr_dma_err,
    output          axim_awlock,
    output  [3:0]   axim_awcache,
    output  [2:0]   axim_awprot,
    output  [3:0]   axim_awqos,
    output  [31:0]  axim_awaddr,
    output  [7:0]   axim_awlen,
    output  [2:0]   axim_awsize,
    output  [1:0]   axim_awburst,
    output          axim_awvalid,
    input           axim_awready,
    output  [63:0]  axim_wdata,
    output  [7:0]   axim_wstrb,
    output          axim_wlast,
    output          axim_wvalid,
    input           axim_wready,
    input   [1:0]   axim_bresp,
    input           axim_bvalid,
    output          axim_bready,
    output          axim_arlock,
    output  [3:0]   axim_arcache,
    output  [2:0]   axim_arprot,
    output  [3:0]   axim_arqos,
    output  [31:0]  axim_araddr,
    output  [7:0]   axim_arlen,
    output  [2:0]   axim_arsize,
    output  [1:0]   axim_arburst,
    output          axim_arvalid,
    input           axim_arready,
    input   [63:0]  axim_rdata,
    input   [1:0]   axim_rresp,
    input           axim_rlast,
    input           axim_rvalid,
    output          axim_rready,
    output  [7:0]   axim_awid,
    input   [7:0]   axim_bid,
    output  [7:0]   axim_arid,
    input   [7:0]   axim_rid
);

wire  [31:0]  csr_dma_err_addr          ;
wire          csr_dma_err_clr           ;
wire  [1:0]   csr_dma_err_type          ;
wire  [7:0]   csr_dma_maxburst          ;
wire  [31:0]  csr_dma_single_trans_bytes;
wire          csr_dma_start             ;
wire  [1:0]   csr_dma_status            ;
wire  [31:0]  csr_dma_total_trans_bytes ;
wire  [31:0]  csr_dst_addr              ;
wire  [31:0]  csr_dst_jump_gap          ;
wire  [15:0]  csr_dst_jump_num          ;
wire  [15:0]  csr_dst_jump_state        ;
wire  [31:0]  csr_src_addr              ;
wire  [31:0]  csr_src_jump_gap          ;
wire  [15:0]  csr_src_jump_num          ;
wire  [15:0]  csr_src_jump_state        ;

// Instance: u_dma_csr (dma_csr)
dma_csr u_dma_csr (
    .clk                        (clk                       ),    // input 
    .rst_n                      (rst_n                     ),    // input 
    .psel                       (psel                      ),    // input 
    .penable                    (penable                   ),    // input 
    .pwrite                     (pwrite                    ),    // input 
    .paddr                      (paddr                     ),    // input  [11:0]
    .pwdata                     (pwdata                    ),    // input  [31:0]
    .prdata                     (prdata                    ),    // output [31:0]
    .pready                     (pready                    ),    // output
    .pslverr                    (pslverr                   ),    // output
    .csr_dma_version            (16'habcd                  ),    // input  [15:0]
    .csr_dma_start              (csr_dma_start             ),    // output
    .csr_dma_maxburst           (csr_dma_maxburst          ),    // output [7:0]
    .csr_dma_single_trans_bytes (csr_dma_single_trans_bytes),    // output [31:0]
    .csr_dma_total_trans_bytes  (csr_dma_total_trans_bytes ),    // output [31:0]
    .csr_src_addr               (csr_src_addr              ),    // output [31:0]
    .csr_dst_addr               (csr_dst_addr              ),    // output [31:0]
    .csr_src_jump_num           (csr_src_jump_num          ),    // output [15:0]
    .csr_dst_jump_num           (csr_dst_jump_num          ),    // output [15:0]
    .csr_src_jump_gap           (csr_src_jump_gap          ),    // output [31:0]
    .csr_dst_jump_gap           (csr_dst_jump_gap          ),    // output [31:0]
    .csr_src_jump_state         (csr_src_jump_state        ),    // input  [15:0]
    .csr_dst_jump_state         (csr_dst_jump_state        ),    // input  [15:0]
    .csr_dma_status             (csr_dma_status            ),    // input  [1:0]
    .csr_dma_err                (intr_dma_err              ),    // input 
    .csr_dma_done               (intr_dma_done             ),    // input 
    .csr_dma_err_clr            (csr_dma_err_clr           ),    // output
    .csr_dma_err_type           (csr_dma_err_type          ),    // input  [1:0]
    .csr_dma_err_addr           (csr_dma_err_addr          )     // input  [31:0]
);

// Instance: u_dma_core (dma_core)
dma_core u_dma_core (
    .clk                        (clk                       ),    // input 
    .rst_n                      (rst_n                     ),    // input 
    .csr_dma_single_trans_bytes (csr_dma_single_trans_bytes),    // input  [31:0]
    .csr_dma_total_trans_bytes  (csr_dma_total_trans_bytes ),    // input  [31:0]
    .csr_src_addr               (csr_src_addr              ),    // input  [31:0]
    .csr_dst_addr               (csr_dst_addr              ),    // input  [31:0]
    .csr_src_jump_num           (csr_src_jump_num          ),    // input  [15:0]
    .csr_dst_jump_num           (csr_dst_jump_num          ),    // input  [15:0]
    .csr_src_jump_gap           (csr_src_jump_gap          ),    // input  [31:0]
    .csr_dst_jump_gap           (csr_dst_jump_gap          ),    // input  [31:0]
    .csr_src_jump_state         (csr_src_jump_state        ),    // output [15:0]
    .csr_dst_jump_state         (csr_dst_jump_state        ),    // output [15:0]
    .csr_dma_start              (csr_dma_start             ),    // input 
    .csr_dma_done               (intr_dma_done             ),    // output
    .csr_dma_status             (csr_dma_status            ),    // output [1:0]
    .csr_dma_err_clr            (csr_dma_err_clr           ),    // input 
    .csr_dma_err                (intr_dma_err              ),    // output
    .csr_dma_err_type           (csr_dma_err_type          ),    // output [1:0]
    .csr_dma_err_addr           (csr_dma_err_addr          ),    // output [31:0]
    .csr_dma_maxburst           (csr_dma_maxburst          ),    // input  [7:0]
    .axim_awlock                (axim_awlock               ),    // output
    .axim_awcache               (axim_awcache              ),    // output [3:0]
    .axim_awprot                (axim_awprot               ),    // output [2:0]
    .axim_awqos                 (axim_awqos                ),    // output [3:0]
    .axim_awaddr                (axim_awaddr               ),    // output [31:0]
    .axim_awlen                 (axim_awlen                ),    // output [7:0]
    .axim_awsize                (axim_awsize               ),    // output [2:0]
    .axim_awburst               (axim_awburst              ),    // output [1:0]
    .axim_awvalid               (axim_awvalid              ),    // output
    .axim_awready               (axim_awready              ),    // input 
    .axim_wdata                 (axim_wdata                ),    // output [63:0]
    .axim_wstrb                 (axim_wstrb                ),    // output [7:0]
    .axim_wlast                 (axim_wlast                ),    // output
    .axim_wvalid                (axim_wvalid               ),    // output
    .axim_wready                (axim_wready               ),    // input 
    .axim_bresp                 (axim_bresp                ),    // input  [1:0]
    .axim_bvalid                (axim_bvalid               ),    // input 
    .axim_bready                (axim_bready               ),    // output
    .axim_arlock                (axim_arlock               ),    // output
    .axim_arcache               (axim_arcache              ),    // output [3:0]
    .axim_arprot                (axim_arprot               ),    // output [2:0]
    .axim_arqos                 (axim_arqos                ),    // output [3:0]
    .axim_araddr                (axim_araddr               ),    // output [31:0]
    .axim_arlen                 (axim_arlen                ),    // output [7:0]
    .axim_arsize                (axim_arsize               ),    // output [2:0]
    .axim_arburst               (axim_arburst              ),    // output [1:0]
    .axim_arvalid               (axim_arvalid              ),    // output
    .axim_arready               (axim_arready              ),    // input 
    .axim_rdata                 (axim_rdata                ),    // input  [63:0]
    .axim_rresp                 (axim_rresp                ),    // input  [1:0]
    .axim_rlast                 (axim_rlast                ),    // input 
    .axim_rvalid                (axim_rvalid               ),    // input 
    .axim_rready                (axim_rready               ),    // output
    .axim_awid                  (axim_awid                 ),    // output [7:0]
    .axim_bid                   (axim_bid                  ),    // input  [7:0]
    .axim_arid                  (axim_arid                 ),    // output [7:0]
    .axim_rid                   (axim_rid                  )     // input  [7:0]
);

endmodule